spring:
  application:
    name: roddy
  profiles:
    active: local # 기본 실행 환경을 local로 지정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret:
    key: ${JWT_SECRET_KEY:ZmFrZS1qd3Qtc2VjcmV0LWtleS1mb3ItbG9jYWwtZGV2ZWxvcG1lbnQta2VlcC1pdC1sb25n}
  expiration:
    access-token: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
    refresh-token: ${JWT_REFRESH_TOKEN_EXPIRATION:1209600000}

app:
  oauth2:
    redirect-uri: ${APP_OAUTH2_REDIRECT_URI:http://localhost:3000/oauth2/redirect}

---
# [Local 환경 설정] - 개발자 PC에서 켤 때
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME:roddy}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 개발 환경이므로 엔티티 변경 시 DB 자동 수정 허용
    show-sql: true # SQL 로그 출력 (개발 중 디버깅 용도)
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - profile
              - email

---
# [Prod 환경 설정] - 나중에 실제 AWS 서버에 배포할 때
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${AWS_DB_URL}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate # 운영 서버는 테이블을 절대 건드리지 않고, 맞게 생성되어 있는지만 검증!
    show-sql: false # 운영 서버 성능 저하 및 보안 이슈 방지를 위해 로그 끄기
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
